# Site settings
title: Südafrika
client:
  name: Client Name
  link: "https://www.southafrica.net/de/de/travel"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Eine Safari ist mehr als nur Wildtierbeobachtung. In Südafrika gehen Sie auf Großstadt-Safari in Johannesburg, auf Gourmet-Safari in Weingütern und auf Küstensafari auf über 3.000 Strandkilometern.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/2020/suedafrika" # the subpath of your site, e.g. /blog/
img:     "/de/2020/suedafrika/_assets/img"
css:     "/de/2020/suedafrika/_assets/css"
js:      "/de/2020/suedafrika/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
